{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Weather forecast",
   "type": "logs",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "environment.outside.pressure.prediction.quadrant",
     "select": [
      [
       { "params": [ "stringValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind forecast",
   "type": "logs",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "environment.outside.pressure.prediction.beaufort",
     "select": [
      [
       { "params": [ "stringValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside feels like",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.outside.heatIndexTemperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 273.15" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.speedOverGround",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.943844" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.directionTrue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*180 / 3.1459" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.outside.humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Baro",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.outside.pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "alias": "Base",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.speedOverGround",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.943844" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Gust",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.speedOverGround",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 1.943844" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Apparent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.speedApparent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.943844" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "TWA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.wind.directionTrue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*180 / 3.1459" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "environment.outside.pressure.system",
     "select": [
      [
       { "params": [ "stringValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "environment.sun",
     "select": [
      [
       { "params": [ "stringValue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Baro",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.outside.pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}