---
galaxy_info:
  role_name: varanny
  author: bergie
  description: Configure VARA HF modem with varanny remote control on Raspberry Pi
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - hamradio
    - vara
    - varanny
    - raspberry-pi