---
- name: S/Y Lille Oe info display computer
  hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes
  vars:
    hostname: infodisplay
    timezone: UTC
    kiosk_url: http://192.168.2.105//@meri-imperiumi/signalk-infodisplay/
  pre_tasks:
    - name: Update apt cache
      apt: null
    - name: Set timezone
      timezone:
        name: "{{ timezone }}"
  tasks:
    - name: Ensure group "crew" exists
      ansible.builtin.group:
        name: crew
        state: present
    - name: Add the pi user
      ansible.builtin.user:
        name: pi
        shell: /bin/bash
        groups: crew
        append: true
    - name: Ensure panel in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: panel
        value: wfrespawn wf-panel-pi
    - name: Ensure background in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: background
        value: wfrespawn pcmanfm --desktop --profile LXDE-pi
    - name: Ensure xdg-autostart in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: xdg-autostart
        value: lxsession-xdg-autostart
    - name: Ensure Chromium in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: chromium
        value: chromium-browser "{{ kiosk_url }}" --kiosk --noerrdialogs
          --disable-infobars --no-first-run --ozone-platform=wayland
          --enable-features=OverlayScrollbar --start-maximized
    - name: Ensure screensaver in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: screensaver
        value: "false"
    - name: Ensure dpms in Wayfire.ini
      community.general.ini_file:
        path: /home/pi/.config/wayfire.ini
        section: autostart
        option: dpms
        value: "false"
    - name: Deploy SSH keys for bergie
      authorized_key:
        user: pi
        state: present
        key: https://github.com/bergie.keys
    - name: Deploy SSH keys for cannonerd
      authorized_key:
        user: pi
        state: present
        key: https://github.com/cannonerd.keys
    - name: Autoremove any unused packages
      apt:
        autoremove: yes
    - name: Autoclean the system
      apt:
        autoclean: yes
