---
- name: S/Y Lille Oe Onboard Computer
  hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  vars:
    hostname: lille-oe-pi
    timezone: UTC
    timers:
      logbook_backup:
        exec_start: /home/pi/log/.github/backup.sh
        user: pi
        group: pi
        on_calendar: hourly
        persistent: true
      logbook_print:
        exec_start: node /home/pi/logbook-printer/index.mjs
        user: pi
        group: pi
        on_calendar: '*:0/15'
        persistent: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Ensure Python venv
      apt:
        name: python3-venv
        state: present

  roles:
    - role: marinepi-provisioning/roles/common
    - role: node-ble
    - role: marinepi-provisioning/roles/signalk-npm
      signalk_settings_file: "{{ inventory_dir }}/signalk/settings.json"
    - role: marinepi-provisioning/roles/influxdb
    - role: marinepi-provisioning/roles/grafana
      grafana_port: 3000
    - role: marinepi-provisioning/roles/canboat
    - alphanodes.setup.systemd_timer

  tasks:
    - name: Deploy SSH keys for bergie
      authorized_key:
        user: pi
        state: present
        key: https://github.com/bergie.keys
    - name: Deploy SSH keys for cannonerd
      authorized_key:
        user: pi
        state: present
        key: https://github.com/cannonerd.keys
    - name: Audio notification dependencies
      ansible.builtin.apt:
        pkg:
          - festival
          - festvox-kallpc16k
          - mpg123
    - name: Restart signalk-server
      service:
        name: signalk-server
        state: restarted
    - name: Clone [b]log repository
      ansible.builtin.git:
        repo: 'git@github.com:meri-imperiumi/log.git'
        dest: /home/pi/log
    - name: Clone printer repository
      ansible.builtin.git:
        repo: 'https://github.com/meri-imperiumi/logbook-printer.git'
        dest: /home/pi/logbook-printer
  handlers:
    - include: ../roles/marinepi-provisioning/handlers/handlers.yml
