grafana_admin_password: ENC[AES256_GCM,data:42BF/NFeO+iRYl2f,iv:BiqJtA3DZwZQvpPHYD42J50AN1Vki4dWTeyNZnC2pv0=,tag:8IIXWZtvHyeGpjHj21hkvA==,type:str]
grafana_secret: ENC[AES256_GCM,data:eKxBduGlMx8r22Z7,iv:zxGuif8gNFeLjquw7pya9Qo7AkSpw6dvB+97LK16A3A=,tag:dpu99RFNS0T2VgaIamwi4Q==,type:str]
sops:
    encrypted_regex: ^(grafana_admin_password|grafana_secret|samba_password|aws_iot.*)$
    lastmodified: "2026-08-12T18:31:10Z"
    mac: ENC[AES256_GCM,data:qJHsQ+7Oq/SIqDVv9UAXlPco6dw0rCptNZq9bPumlAnTDys1Emoi4HsLwADxKgBHV7ybcPgizZgi3R6QpC5o4BH105BNgBH2PGiYv4ToRb4gwuktEI3JJT+9AMkXKlf/YoT87DiHS3zfHibPF5RtadPM86uWO03gN9gaY68kkWk=,iv:LWoQl3hMVifwWPmBzDETwFE1KyHww7pQm4F7ZKt81ug=,tag:lCS/YzNGRsINVPlrqbbRWg==,type:str]
    pgp:
        - created_at: "2026-08-12T18:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA25ZXxdyTrfzARAAmAFav3NWWMxcX9rHHlaPqfoTd8bY/eFGgU3Z6Y6S2cq7
            s04zKJ/2Rcs/GmXrWR1bONOhqF7safIIcIa9ihEeGvLHEgm4/u388KzFT/KlnQiI
            /mrJnm6/Jy8OB4aiuM/rFBcrB/i8JihgJllL/HTThygSl2VrZBoxpzEs3Sm8APjH
            scXcGwpHYpqGC6zp61VvHhIbxwJNtPWfo7EZqPWCcctxVQdQ/89IBjjN+gvPWK6b
            EjE+hpemSLxooxYSCCTFZfmCiZ4mMiIdtsL2h1F41QWIB1zAnqJvQQa0CMJRVeAF
            kwURTUCHWmBNbY9u3bphnOC3PXKBmODB32gr3Q0KJ464bLIVw3PdwP7LdP8mL20c
            KoaA7g4o607ae7PyfG257uv3UYfx2OY+NYWFf4Rr7Nd2UjrC7w9FzaI/l4e4ZtHA
            ajzKwwJKXlxBKJKXT14MXGF9SjELq27sZjzXQllmZ0MTZHxynICw/erT/1UdQDf3
            1nE82NCF2V0t9xcgDFEkZXUSCe4hVkLY2e1FDP++tHxAybN/dhaUyxE6+O4HCSlH
            vqHF5bzewPvFodujlkvQGHxPI9NjzXDdLHmNw8D+w+V5FraUBIrlNuJXKNlrMQtU
            NFLjLw2qiKMx2KGddC/1xYNlIIOgeR0usqfJTnGYjjr7W/t81G2VyA+n48r4md7S
            UQGFZKzr5H8yetIyZnEtzqijp4s6L0T7vIlU2fMRsr4sKK94mMat/iL0pXsbdYz8
            v2P/lNMDscq+2YmQicN0bLjH0dI2oixMptqDpGOLuic9Zw==
            =IzMD
            -----END PGP MESSAGE-----
          fp: 39D337CCE31E2D75D6121959FF9EAEBA76E18617
    version: 3.13.3
