samba_password: ENC[AES256_GCM,data:TsbyeQNUsDM8,iv:5MknSJZRP78zjV/xudBjuq4KURCSKgoiDWAxNMuDmLc=,tag:fdjUMLutRGEwWTNMBRQkUw==,type:str]
sops:
    encrypted_regex: ^(grafana_admin_password|grafana_secret|samba_password|aws_iot.*)$
    lastmodified: "2026-08-12T18:30:19Z"
    mac: ENC[AES256_GCM,data:1Mw6caBo191JLqVEgm6TY9Ne8m+3l+1qNgySpoT7cMHi7Pkmp8lcCFz7/RcwyBpvir2WPp784owhXz4rw0yo5KvSBsFsspH8e9zElHHHgsbOVX+Cp3d0ccu/jYtXs+P0GPnjR4QGInRjuEiP3Gj1kKIL/DRD+kxxPt/LNyRxcLA=,iv:LC7yMeFY/EcwaEePMMK35pAu7sapjlbMDa8/WHJmrm8=,tag:nMFtMaEHEmaqpqsun7fQCg==,type:str]
    pgp:
        - created_at: "2026-08-12T18:30:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA25ZXxdyTrfzAQ/7BFog0wZYz+4n7tIrGngNlYjHh7kDPECQZFiWIfHcPCjB
            Rh7v8uCcmxd8s5TNKUyxBVLoUA22pfmbZA/3ui0NX98jaf4TzgvRfXQTqSH5/reX
            HlUIIohaQlPa/lAE+8u+hQL/fSPWQkzUqDqqpA6LX3rtuYwGCcq6fx8GAxJZQB1m
            OB8/WCLmtVNYjmk7SzfJrajSrv70L/AmL5zo2QyaVNx6/zvlxmkbggLHJWmBPBbg
            SSfP422kebRVOoAmKq+O4+CkgRvJF0smr/VAKMmCQde4yM5Kuk8GrHE6IsIhk5jy
            TH2X/grcfweVEDHIUOac2X8GF6QWmpcbP6k8wtWG8FHIdA6mfElxVE8OwULqmzPG
            LlSU9+nG/P01dJTF3C46eyLbazSfXQ5RPTLNkw+gCQWZCeJPzwqWayEowrFAs32g
            Ns/rTfjngoOIGk7FcyW/FDrdLFmP27vnA7XQFY/q4T5ZZzx25A4eYz5laz31Z4WY
            kirL2NLLP5aQmkQ9mdkKwaLFEx/zU2IohqI1x79WoL3kSukYftJPrzpgegTGcS+/
            IodAvYuFERgRpHqqjU/tESoj+ENB466iJq3/y1N2d3/3QEswtnn8DdzydVycbXoj
            dyWyWm0m5m15Ztj+3k7hyT3Kv6PL4Qj96mbY1J5iyPpuEYJA+wM+FMq01gvuxEfS
            UQGROTKIqATZuSyCiPeOW7vhUAR268LqrpnmClv/mthNc2ROXfoz2TEWJayGCLjh
            HNpjD42oqFTZ8gtZvoltNDqgYhjJy2E1al5sdz+cRNL5KQ==
            =r9Cz
            -----END PGP MESSAGE-----
          fp: 39D337CCE31E2D75D6121959FF9EAEBA76E18617
    version: 3.13.3
